// utils/fakeBuses.js
const getRandomSeatOccupancy = () => Math.floor(Math.random() * 51) + 10; // between 10–60 seats filled
const getRandomETA = () => `${Math.floor(Math.random() * 20) + 1} mins`; // 1–20 mins

const fakeBuses = [
  {
    id: "BUS001",
    company: "Yash",
    status: "driving",
    lat: 23.8103,
    lng: 90.4125,
    alerts: { overspeed: true, unplugged: false },
    seatOccupancy: getRandomSeatOccupancy(),
    expectedArrivalTime: getRandomETA(),
  },
  {
    id: "BUS002",
    company: "Mayank",
    status: "idle",
    lat: 23.7506,
    lng: 90.3933,
    alerts: { overspeed: false, unplugged: false },
    expectedArrivalTime: getRandomETA(),
  },
  {
    id: "BUS003",
    company: "Chirag",
    status: "depot",
    lat: 23.9,
    lng: 90.32,
    alerts: { overspeed: false, unplugged: true },
    expectedArrivalTime: getRandomETA(),
  },
  {
    id: "BUS004",
    company: "Sujal",
    status: "offline",
    lat: 23.7104,
    lng: 90.4074,
    alerts: { overspeed: false, unplugged: false },
  },
  {
    id: "BUS005",
    company: "Nidhi",
    status: "driving",
    lat: 23.7800,
    lng: 90.4000,
    alerts: { overspeed: true, unplugged: false },
    seatOccupancy: getRandomSeatOccupancy(),
    expectedArrivalTime: getRandomETA(),
  },
  {
    id: "BUS006",
    company: "Divya",
    status: "idle",
    lat: 23.7700,
    lng: 90.4200,
    alerts: { overspeed: false, unplugged: true },
    expectedArrivalTime: getRandomETA(),
  },
  {
    id: "BUS007",
    company: "GreenLine",
    status: "depot",
    lat: 23.7600,
    lng: 90.4300,
    alerts: { overspeed: false, unplugged: false },
    expectedArrivalTime: getRandomETA(),
  },
  {
    id: "BUS008",
    company: "Hanif",
    status: "offline",
    lat: 23.7500,
    lng: 90.4100,
    alerts: { overspeed: false, unplugged: true },
  },
  {
    id: "BUS009",
    company: "Shohag",
    status: "driving",
    lat: 23.7400,
    lng: 90.4000,
    alerts: { overspeed: true, unplugged: false },
    seatOccupancy: getRandomSeatOccupancy(),
    expectedArrivalTime: getRandomETA(),
  },
  {
    id: "BUS010",
    company: "GreenLine",
    status: "idle",
    lat: 23.7300,
    lng: 90.4200,
    alerts: { overspeed: false, unplugged: false },
    expectedArrivalTime: getRandomETA(),
  },
  // ... continue this same pattern for all 20 buses
];

export default fakeBuses;